### ISSUE TITLE
node date doesn't support formatString argument

### ISSUE THREAD

**Issue by JAugustJackson** [uptimeventures/gatsby-source-rss#2]
Otherwise, this works great. Great plugin!

**Comment by secretfader** [comment]
Thanks for the report, @JoshMormann. I don't use this plugin myself all that much, so it's no surprise I missed the `formatString` incompatibility.

That said, I'm looking to hand off maintenance and new feature work to someone else, possibly the Gatsby community at large. (I've intended to kick off talks about moving this plugin into the Gatsby monorepo, but had too many items on my plate to begin in earnest.)

Would you be interested in submitting a PR to resolve this issue?

**Comment by secretfader** [comment]
This issue should be resolved by #3, which I'll be releasing in just a few minutes. Thanks to @thomascarvalho for stepping in with the fix.

@JoshMormann, if this doesn't resolve your issue, feel free to reopen and maybe I'll take a second stab at it. But my hunch is you should be good to go once the latest version is installed from npm. :)
